### PR TITLE
Remove offensive term

### PR DESCRIPTION
**Pull request by briandonahue**
As someone who used that term when I was younger and later realized the impact it had on many people, just a friendly suggestion that maybe you don't want to use it, and/or have your company associated with it.

### CODE REVIEW

**Comment by danielbachhuber** [comment]
Thanks @briandonahue — good point

**Comment by briandonahue** [comment]
Thanks @danielbachhuber!  Now, to find the time to port this to our hubot instance :)

**Comment by danielbachhuber** [comment]
> Now, to find the time to port this to our hubot instance :)

I'd be curious to know how you feel Hubot and Superscript compare. As we consider building more Slack bots, it seems like we should pick one or the other.

cc @noppanit

**Comment by briandonahue** [comment]
@danielbachhuber I will share if I get to it, but if recent history is any indicator, it will probably be on the "some day" list for a while :disappointed:

**Comment by briandonahue** [comment]
@danielbachhuber I actually hadn't looked at superscript before, so now you have me thinking about that, too...  we just picked hubot because it was fairly easy to get the defaults and a few extra scripts up and running.

**Comment by noppanit** [comment]
@briandonahue I haven't looked at Hubot either. That got me curious as well. I'll take a look. How's your experience so far in terms of building new plugin? Or adding new answers?

**Comment by briandonahue** [comment]
I have only dabbled and read source of other scripts.  It looks fairly
straightforward, but it doesn't have the built in language intelligence
that Superscript seems to have.  Seems like most of the examples are regex
based.  Is it fairly straightforward in SS to make a bot that calls out to
APIs, etc?  E.g. we use one for our CI system "deploy <project> to <env>"

**Comment by noppanit** [comment]
Yes It's quite straightforward. We just need to do this. 

https://github.com/fusioneng/rubberduck-bot/pull/8/files#diff-7e7d8bed4dea112afcf1b938f62fce2aR19

And that would call the plugin by name.

**Pull request merged**
